# Generated by Django 5.0.6 on 2024-07-01 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
