# Generated by Django 5.0.6 on 2024-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tax_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='id_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Student', 'طالب'), ('Instructor', 'معلم'), ('Manager', 'مشرف'), ('Families', 'عائله'), ('Admin', 'ادمن')], default='Manager', max_length=50),
        ),
    ]
