# Generated by Django 5.0.6 on 2024-07-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_families_id_number_alter_customuser_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
    ]
