# Generated by Django 5.0.6 on 2024-07-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_class_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number_class_hours',
            field=models.CharField(choices=[('40', '40 دقيقه'), ('45', '45 دقيقه'), ('60', '60 دقيقه'), ('80', '80 دقيقه'), ('90', '90 دقيقه'), ('120', '120 دقيقه')], default='40', max_length=50),
        ),
    ]
