# Generated by Django 5.0.6 on 2024-07-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_classes_number_class_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='nb',
            new_name='notes',
        ),
    ]
