# Generated by Django 5.0.6 on 2024-07-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_classes_instructor_familyinvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorinvoice',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='studentinvoice',
            name='student',
        ),
        migrations.DeleteModel(
            name='FamilyInvoice',
        ),
        migrations.DeleteModel(
            name='InstructorInvoice',
        ),
        migrations.DeleteModel(
            name='StudentInvoice',
        ),
    ]
