# Generated by Django 5.0.6 on 2024-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_instructorinvoice_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number_class_hours',
            field=models.CharField(choices=[('1', '1 ساعه'), ('2', '2 ساعه'), ('3', '3 ساعه'), ('4', '4 ساعه'), ('5', '6 ساعه')], default='1', max_length=50),
        ),
    ]
