# Generated by Django 5.0.6 on 2024-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_classes_number_class_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='hourly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='hourly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
