# Generated by Django 5.0.6 on 2024-07-04 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_instructor_hourly_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='number',
        ),
        migrations.AddField(
            model_name='billingmonths',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.families'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tax',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
