# Generated by Django 5.0.6 on 2024-07-06 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_tax_number_billingmonths_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='families',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
