# Generated by Django 5.0.6 on 2024-07-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_families_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advances_Discounts',
            new_name='Discounts',
        ),
    ]
