# Generated by Django 5.0.6 on 2024-07-06 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_advances_discounts_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discounts',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='discounts',
            name='date',
        ),
    ]
