# Generated by Django 5.0.6 on 2024-07-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_discounts_comment_remove_discounts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='comment',
            field=models.CharField(default='ss', max_length=250),
            preserve_default=False,
        ),
    ]
