# Generated by Django 5.0.6 on 2024-07-16 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_customuser_type_marketer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketer_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.families')),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.marketer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
    ]
