# Generated by Django 5.0.6 on 2024-07-16 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_marketer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer_student',
            name='marketer',
            field=models.ForeignKey(limit_choices_to={'type': 'Marketer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
