# Generated by Django 5.0.6 on 2024-07-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_marketer_student_marketer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marketer',
        ),
    ]
