# Generated by Django 5.0.6 on 2024-08-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_delete_marketer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
