# Generated by Django 5.0.6 on 2024-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='whatsapp',
            field=models.CharField(default=125165165, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='whatsapp',
            field=models.CharField(default=654654, max_length=16),
            preserve_default=False,
        ),
    ]
