# Generated by Django 5.0.6 on 2024-08-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_families_whatsapp_instructor_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='whatsapp',
        ),
    ]
