# Generated by Django 5.0.6 on 2024-08-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_instructor_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='class_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
