# Generated by Django 5.0.6 on 2024-08-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_instructor_class_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='user',
        ),
        migrations.RemoveField(
            model_name='families',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='families',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='families',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'ذكر'), ('Female', 'انثى')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='families',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='families',
            name='name',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='families',
            name='number',
            field=models.IntegerField(default=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Marketer', 'مسوق'), ('Instructor', 'معلم'), ('Manager', 'مشرف'), ('Admin', 'ادمن')], default='Manager', max_length=50),
        ),
        migrations.AlterField(
            model_name='families',
            name='payment_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='id_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
