# Generated by Django 5.0.6 on 2024-08-09 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_families_user_remove_families_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='families',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
