# Generated by Django 5.0.6 on 2024-08-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_families_created_at_alter_families_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='families',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='families',
            name='gender',
            field=models.CharField(choices=[('Male', 'ذكر'), ('Female', 'انثى')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='families',
            name='the_state',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
