# Generated by Django 5.0.6 on 2024-08-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_marketer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketer',
            name='ratio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
