# Generated by Django 5.0.6 on 2024-08-11 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_marketer_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='marketer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.marketer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classes',
            name='number_class_hours',
            field=models.CharField(choices=[('1', '30 دقيقة'), ('2', '45 دقيقة'), ('3', '60 دقيقة'), ('4', '90 دقيقة'), ('5', '120 دقيقة')], default='1', max_length=50),
        ),
    ]
