# Generated by Django 5.0.6 on 2024-08-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_discounts_marketer_alter_classes_number_class_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.instructor'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.marketer'),
        ),
    ]
