# Generated by Django 5.0.6 on 2024-08-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_discounts_instructor_alter_discounts_marketer'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
