# Generated by Django 5.0.6 on 2024-08-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_discounts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
