# Generated by Django 5.0.6 on 2024-08-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_marketer_ratio_alter_marketer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='number_class_hours',
            field=models.CharField(choices=[('30', '30 دقيقة'), ('45', '45 دقيقة'), ('60', '60 دقيقة'), ('90', '90 دقيقة'), ('120', '120 دقيقة')], default='30', max_length=50),
        ),
    ]
