# Generated by Django 5.0.6 on 2024-08-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_classes_number_class_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
