# Generated by Django 5.0.6 on 2024-08-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_marketer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
