# Generated by Django 5.0.6 on 2024-08-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_marketer_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='families',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='instructor_student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='marketer_student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
    ]
