# Generated by Django 5.0.6 on 2024-08-16 16:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_classes_options_alter_families_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
