# Generated by Django 5.0.6 on 2024-08-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_families_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='phone_number',
        ),
    ]
