# Generated by Django 5.0.6 on 2024-08-16 17:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_families_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='families',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
