# Generated by Django 5.0.6 on 2024-08-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='how_it_works',
            options={'verbose_name_plural': 'How it works'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name_plural': 'Terms'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='whyus',
            options={'verbose_name_plural': 'Why us'},
        ),
    ]
