# Generated by Django 5.0.6 on 2024-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Testimonials Video',
            },
        ),
    ]
