# Generated by Django 5.0.6 on 2024-08-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='a', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
