# Generated by Django 5.0.6 on 2024-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='as', upload_to='blog_images'),
            preserve_default=False,
        ),
    ]
