# Generated by Django 5.0.6 on 2024-08-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=12, null=True)),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/logo')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phones', models.CharField(blank=True, max_length=100, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
