# Generated by Django 5.0.6 on 2024-08-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='EMAIL',
            new_name='email',
        ),
    ]
