# Generated by Django 5.0.6 on 2024-08-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tutors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact us'},
        ),
        migrations.AlterModelOptions(
            name='fees',
            options={'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name_plural': 'Pricing'},
        ),
        migrations.AlterModelOptions(
            name='pricing_content',
            options={'verbose_name_plural': 'Pricing Content'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterModelOptions(
            name='teachercontact',
            options={'verbose_name_plural': 'Teacher Contact'},
        ),
        migrations.AlterModelOptions(
            name='tutors',
            options={'verbose_name_plural': 'Tutors'},
        ),
    ]
