# Generated by Django 5.0.6 on 2024-08-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_teachercontact_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='video',
            field=models.CharField(default='aaaaaaa', max_length=1000),
            preserve_default=False,
        ),
    ]
