# Generated by Django 5.0.6 on 2024-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_settings_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('min_class', models.CharField(choices=[('min30', '30 Min'), ('min45', '45 Min'), ('min60', '60 Min')], max_length=15)),
                ('plan', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
