# Generated by Django 5.0.6 on 2024-09-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pricecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricecontact',
            name='subject',
        ),
    ]
